###
GET http://localhost:8080/hello?name=anxiaole


### 可以直接传json数组
GET http://localhost:8080/helloList
Content-Type: application/json

[
  {
    "id": 1,
    "name": "xx",
    "userName": "用户名",
    "fageXx": "11",
    "fAddressXx": "河北"
  },
  {
    "id": 21,
    "name": "2xx",
    "userName": "2用户名",
    "fageXx": "211",
    "fAddressXx": "2河北"
  }
]



###
GET http://localhost:8080/json

###
POST http://localhost:8080/moreRequestBodyParam
Content-Type: application/json

{
  "detailAddress": "北京市丰台区xxx大厦",
  "userName": "安小乐"
}
